spring.application.name=lessonflow
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=LessonFlow

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/

spring.ai.openai.api-key=${OPEN_AI_KEY}
#For debugging (optional):
logging.level.org.springframework.ai.chat.client.advisor=DEBUG